from quiz.models import Question

questions = [
    {"text": "What is the capital of France?", "option_a": "Berlin", "option_b": "Madrid", "option_c": "Paris", "option_d": "Rome", "correct_option": "C"},
    {"text": "Which planet is known as the Red Planet?", "option_a": "Venus", "option_b": "Mars", "option_c": "Jupiter", "option_d": "Saturn", "correct_option": "B"},
    {"text": "What is the largest ocean on Earth?", "option_a": "Atlantic", "option_b": "Indian", "option_c": "Arctic", "option_d": "Pacific", "correct_option": "D"},
    {"text": "Who wrote 'Romeo and Juliet'?", "option_a": "Mark Twain", "option_b": "William Shakespeare", "option_c": "Charles Dickens", "option_d": "J.K. Rowling", "correct_option": "B"},
    {"text": "What is the smallest prime number?", "option_a": "1", "option_b": "2", "option_c": "3", "option_d": "5", "correct_option": "B"},
    {"text": "What is the chemical symbol for water?", "option_a": "H2O", "option_b": "O2", "option_c": "CO2", "option_d": "HO", "correct_option": "A"},
    {"text": "Who painted the Mona Lisa?", "option_a": "Vincent van Gogh", "option_b": "Pablo Picasso", "option_c": "Leonardo da Vinci", "option_d": "Claude Monet", "correct_option": "C"},
    {"text": "How many continents are there?", "option_a": "5", "option_b": "6", "option_c": "7", "option_d": "8", "correct_option": "C"},
    {"text": "What is the capital of Japan?", "option_a": "Beijing", "option_b": "Seoul", "option_c": "Tokyo", "option_d": "Bangkok", "correct_option": "C"},
    {"text": "Which element has the atomic number 1?", "option_a": "Hydrogen", "option_b": "Helium", "option_c": "Oxygen", "option_d": "Nitrogen", "correct_option": "A"},
    {"text": "What is the square root of 64?", "option_a": "6", "option_b": "7", "option_c": "8", "option_d": "9", "correct_option": "C"},
    {"text": "Which planet is the largest in the solar system?", "option_a": "Saturn", "option_b": "Jupiter", "option_c": "Neptune", "option_d": "Earth", "correct_option": "B"},
    {"text": "What is the national language of Canada?", "option_a": "English", "option_b": "French", "option_c": "Both English and French", "option_d": "Spanish", "correct_option": "C"},
    {"text": "How many sides does a hexagon have?", "option_a": "5", "option_b": "6", "option_c": "7", "option_d": "8", "correct_option": "B"},
    {"text": "What is the powerhouse of the cell?", "option_a": "Nucleus", "option_b": "Mitochondria", "option_c": "Ribosome", "option_d": "Golgi apparatus", "correct_option": "B"},
    {"text": "What is 5 multiplied by 6?", "option_a": "25", "option_b": "30", "option_c": "35", "option_d": "40", "correct_option": "B"},
    {"text": "What is the longest river in the world?", "option_a": "Amazon", "option_b": "Nile", "option_c": "Yangtze", "option_d": "Mississippi", "correct_option": "B"},
    {"text": "Who invented the telephone?", "option_a": "Alexander Graham Bell", "option_b": "Thomas Edison", "option_c": "Nikola Tesla", "option_d": "Guglielmo Marconi", "correct_option": "A"},
    {"text": "What is the capital of Australia?", "option_a": "Sydney", "option_b": "Melbourne", "option_c": "Canberra", "option_d": "Perth", "correct_option": "C"},
    {"text": "What is the speed of light?", "option_a": "3,000 km/s", "option_b": "300,000 km/s", "option_c": "3,000,000 km/s", "option_d": "30,000 km/s", "correct_option": "B"},
    {"text": "What is the boiling point of water in Celsius?", "option_a": "90°C", "option_b": "100°C", "option_c": "110°C", "option_d": "120°C", "correct_option": "B"},
    {"text": "What is the largest mammal?", "option_a": "Elephant", "option_b": "Blue Whale", "option_c": "Giraffe", "option_d": "Hippopotamus", "correct_option": "B"},
    {"text": "What is the hardest natural substance?", "option_a": "Gold", "option_b": "Diamond", "option_c": "Silver", "option_d": "Platinum", "correct_option": "B"},
    {"text": "What is the main ingredient in guacamole?", "option_a": "Tomato", "option_b": "Avocado", "option_c": "Onion", "option_d": "Pepper", "correct_option": "B"},
    {"text": "Which gas do plants primarily use during photosynthesis?", "option_a": "Oxygen", "option_b": "Carbon dioxide", "option_c": "Nitrogen", "option_d": "Hydrogen", "correct_option": "B"},
    {"text": "What is the capital of Italy?", "option_a": "Florence", "option_b": "Venice", "option_c": "Rome", "option_d": "Milan", "correct_option": "C"},
    {"text": "Who discovered gravity?", "option_a": "Albert Einstein", "option_b": "Isaac Newton", "option_c": "Galileo Galilei", "option_d": "Nicolaus Copernicus", "correct_option": "B"},
    {"text": "What is the symbol for gold?", "option_a": "Au", "option_b": "Ag", "option_c": "Pb", "option_d": "Fe", "correct_option": "A"},
    {"text": "What is the process of converting water into vapor called?", "option_a": "Condensation", "option_b": "Evaporation", "option_c": "Precipitation", "option_d": "Sublimation", "correct_option": "B"},
    {"text": "Which country is known as the Land of the Rising Sun?", "option_a": "China", "option_b": "Japan", "option_c": "Korea", "option_d": "Vietnam", "correct_option": "B"},
    {"text": "What is the chemical symbol for oxygen?", "option_a": "O", "option_b": "O2", "option_c": "Ox", "option_d": "O3", "correct_option": "A"},
    {"text": "What is the freezing point of water in Celsius?", "option_a": "0°C", "option_b": "32°C", "option_c": "100°C", "option_d": "4°C", "correct_option": "A"},
    {"text": "Who wrote 'The Origin of Species'?", "option_a": "Charles Darwin", "option_b": "Albert Einstein", "option_c": "Gregor Mendel", "option_d": "Isaac Newton", "correct_option": "A"},
    {"text": "What is the capital of Canada?", "option_a": "Toronto", "option_b": "Vancouver", "option_c": "Ottawa", "option_d": "Montreal", "correct_option": "C"},
    {"text": "Which part of the plant conducts photosynthesis?", "option_a": "Roots", "option_b": "Stem", "option_c": "Leaves", "option_d": "Flowers", "correct_option": "C"},
    {"text": "What is 7 x 8?", "option_a": "48", "option_b": "54", "option_c": "56", "option_d": "64", "correct_option": "C"},
    {"text": "Which gas is most abundant in Earth's atmosphere?", "option_a": "Oxygen", "option_b": "Nitrogen", "option_c": "Carbon dioxide", "option_d": "Hydrogen", "correct_option": "B"},
    {"text": "What is the primary language of Brazil?", "option_a": "Spanish", "option_b": "Portuguese", "option_c": "English", "option_d": "French", "correct_option": "B"},
    {"text": "What is the square root of 144?", "option_a": "10", "option_b": "11", "option_c": "12", "option_d": "13", "correct_option": "C"},
    {"text": "Who developed the theory of relativity?", "option_a": "Albert Einstein", "option_b": "Isaac Newton", "option_c": "Galileo Galilei", "option_d": "Marie Curie", "correct_option": "A"},
    {"text": "What is the largest desert in the world?", "option_a": "Sahara", "option_b": "Gobi", "option_c": "Arctic", "option_d": "Antarctica", "correct_option": "D"},
    {"text": "Which animal is known as the Ship of the Desert?", "option_a": "Horse", "option_b": "Camel", "option_c": "Donkey", "option_d": "Elephant", "correct_option": "B"},
    {"text": "What is 15 divided by 3?", "option_a": "3", "option_b": "5", "option_c": "7", "option_d": "9", "correct_option": "B"},
]

for q in questions:
    Question.objects.create(
        text=q["text"],
        option_a=q["option_a"],
        option_b=q["option_b"],
        option_c=q["option_c"],
        option_d=q["option_d"],
        correct_option=q["correct_option"],
    )
